name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1 
      
    - name: Build Project
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 Project1.vcx.proj
      
    
